Release v1.6.0
airbrake/pybrake pull request #221
Opened 2022-07-07 06:16 UTC by smurf-U

2022-07-07 15:09 UTC, kyrylo requested changes
Let's not mention internal changes in our CHANGELOG. The CHANGELOG is not meant to be a duplicate of the git logs. We must talk to the user and explain what value we added or what public APIs we've changed.

2022-07-07 15:09 UTC, kyrylo commented on changelog.md
> +- Add and Improve code docstring and code refactoring
Let's omit code refactoring entries. They bring no value to our users.

2022-07-07 15:09 UTC, kyrylo commented on changelog.md
> +- Bump pycares from 4.1.2 to 4.2.0 in /examples/aiohttp
Nobody cares about pycares being updated here 😁

2022-07-07 15:09 UTC, kyrylo commented on changelog.md
> +- Fixed AIOHTTP middleware for Error Monitoring
Describe what was fixed.

2022-07-07 15:09 UTC, kyrylo commented on changelog.md
> +- Improve README file
Why would anyone care?

2022-07-08 05:38 UTC, smurf-U commented
PTAL

2022-07-08 09:21 UTC, kyrylo approved these changes

2022-07-08 09:21 UTC, kyrylo commented on changelog.md
> +## [1.6.0] - 2022-07-07
```suggestion
## [1.6.0] - 2022-07-08
```

2022-07-08 09:54 UTC, merged